apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  type: LoadBalancer  # Assigns an external IP
  ports:
  - port: 80          # Public port
    targetPort: 5001  # Container port
  selector:
    app: todo-frontend